### PR TITLE
Update to modern window appearance.

### PR DESCRIPTION
**Pull request by GetToSet**
This PR contains lots of visual updates to adopt modern appearances, which includes:

1. Use separate filters for podcasts and episodes. This helps enabling different filter criterias for podcasts and episodes in future, although currently there's only one 'unplayed' criteria.
2. Refactor `SortingView` into `SortingMenuProvider` that is agnostic to the actual UI, especially, allow providing menus for pull down buttons.
3. Replace the sorting button on episodes view into a `NSPopupButton`. On 10.15, a filtering button on the right is provided. On 11.0 and later, filtering button is provided on the toolbar. Replace the sorting button on podcasts view into an icon-based button that provides both sorting and filtering.
4. Bring the 'View' menu back.
Screen Shot 2022-01-23 at 22 06 07
5. Add minimum column width to the detailView, slightly adjusts minimum column widths and allow collapsing the sidebar.
6. Display selected podcast name and unplayed episode count on titlebar for 11.0 and later OS  if the width is enough.
7. Implement toolbar buttons for common actions like refresh and create podcast.

macOS 12:
Screen Shot 2022-01-23 at 22 09 51

macOS 10.15:
Screenshot 2022-01-23 AM 5 46 22

### CODE REVIEW

**Review by dyerc — APPROVED** [review]
This is excellent @GetToSet , thank you!

Really like the new window interface and sorting buttons 👍

**Comment by woj-tek** [comment]
I just tested new beta version and I ran "into issue" and I think this is the change that introduced it. Previously it was possibly to quickly toggle between view with feeds with new episodes and all feeds, currently this is hidden behind menu at the bottom (which also has filter sub-menu) but instead of single click (to get list only with updated feeds) one has to click on the icon and then navigate to submenu and select "new episodes". Having this handy (or at leasts sticky/remembered between restarts) would be convenient.

**Comment by GetToSet** [comment]
> I just tested new beta version and I ran "into issue" and I think this is the change that introduced it. Previously it was possibly to quickly toggle between view with feeds with new episodes and all feeds, currently this is hidden behind menu at the bottom (which also has filter sub-menu) but instead of single click (to get list only with updated feeds) one has to click on the icon and then navigate to submenu and select "new episodes". Having this handy (or at leasts sticky/remembered between restarts) would be convenient.

Doughnut currently doesn't preserve applied selections, filtering, and sortings during a restart. I'll implement these sorts of state resolutions in future versions.

I prefer not linking the filters of episodes and podcasts together, since they differ in some properties and this makes it hard for future versions to implement filtering by custom criteria.

Apple's [HIG](https://developer.apple.com/design/human-interface-guidelines/macos/menus/contextual-menus/) discourages submenus nested deep in the contextual menu. Some adjustments to the menu or adding keyboard shortcuts might be a solution to this problem. I'll take some more experiments to make filter actions smoother.

**Comment by woj-tek** [comment]
Thank you for the comment (and all the work!). I wasn't suggesting linking of the filters because (as you noted) they are separate between episodes and feed list. I merely suggested to make it more accessible. In case of episode list the button serves as a toggle - maybe something similar could be used in list of feeds (and having two icons/buttons in the bottom section)?

**Pull request merged**
