### PR TITLE
Move PlayerView to the bottom of the main window with a vibrant background

### PR DESCRIPTION
**Pull request by GetToSet**
This PR:
1. Moves `PlayerView` to the bottom of the main window, spanning across two columns except for the sidebar.
2. Replaces the gradient gradient with a visual effect view to provide translucency.

Most Mac apps that plays audio, excluding system ones, ships ships with their playback status view on the bottom. Moving `PlayerView` to the bottom frees space from the toolbar, which allows more room for toolbar action buttons and the future adaptation for Big Sur's sectioned toolbar for split view and allow user to toggle the toolbar off.

`PlayerView` lacks responsiveness since it doesn't use Auto Layout. Current implementation wraps the entire view centered into a full-width view controller, preserving its original content, width and height.

### CODE REVIEW

**Comment by dyerc** [comment]
Thank you very much for putting this together @GetToSet . I can see your reasoning behind wanting to change the toolbar for Big Sur's toolbar split view, however personally I particularly like having the player at the top of the window. The toolbar feels quite empty to me now and a bit bare. Quite happy if anyone else wants to drop their thoughts in, but I'll need to give it some thought.

**Comment by GetToSet** [comment]
> Thank you very much for putting this together @GetToSet . I can see your reasoning behind wanting to change the toolbar for Big Sur's toolbar split view, however personally I particularly like having the player at the top of the window. The toolbar feels quite empty to me now and a bit bare. Quite happy if anyone else wants to drop their thoughts in, but I'll need to give it some thought.

The toolbar is empty after this change, but more toolbar items like reload, subscribe, mark played or favorite and filtering can be put onto the toolbar in the future. Since `PlayerView` is wider than Benitez, there will be more space for controls related to playback such as the volume slider, while allowing users to toggle off the toolbar or the sidebar without losing essential playback controls.

That's why I initiate this change, we could have more discussions, or might better, to hear about others' opinions.

**Comment by GetToSet** [comment]
After some second thoughts, it might be able to migrate to a modern visual style without compromising current interface structure, I'll continue to experiment other possibilities. 🤔

**Comment by woj-tek** [comment]
My 3 cents: first time I saw it I was kinda confused and wasn't sure I liked it but: it does seem to be consistent with the UI direction proposed by Apple (compare with Finder for example). It could even go further and stretch the sidebar all way to the top.

It probably could be possible to have the progressbar still in the top toolbar but with the idea to put there useful command icons (again, like in Finder) it would make the space quite crowded (and even make progress bar smaller). I would argue that the direction is quite good and it would be quite convenient to have progressbar (and playback controls) at the bottom if it would stretch to the whole width of the window (thus making it easier to navigate on the really long podcasts)

**Comment by GetToSet** [comment]
This PR is closed in favor of #47.

**Pull request closed without merging**
